# Site settings
title: "Iulian Ichim"
description: "Resume of Iulian Ichim. Built with Jekyll and Github Pages. Inspired from a Jekyll template by @jglovier."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Iulian Ichim"
resume_title:                   "Bioinformatics Software Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ichim.iulian12@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+353874880410"
resume_contact_address:         "Cork, Ireland"

resume_header_contact_info:     "Cork, Ireland • ichim.iulian12 [~at~] gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I possess a great desire to advance my career with a leading organization that will utilize my extensive bioinformatics knowledge while also allowing me to develop further as a professional. Proven talent for aligning project objectives with established and emerging biotechnology paradigms to achieve optimal results with minimal challenges. Growth-focused leader with expertise spanning research and analysis, application design, critical thinking, problem solving, team collaboration, and organization. Exceptional professional with keen interpersonal, communications, and task prioritization expertise.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
research_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/IulianIV"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/IchimIuli/"
  resume_linkedin_url:          "https://www.linkedin.com/in/iulianichim/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://iulianiv.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
